{
 "title": "Nomad Server",
 "description": "Monitor overall health, and resource usage of a Nomad cluster, Raft usage, RPC usage etc.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(nomad_client_uptime, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (hostname) (nomad_runtime_alloc_bytes{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of objects in heap",
   "type": "timeseries",
   "description": "Number of objects on the heap. General memory pressure indicator",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (hostname) (nomad_runtime_heap_objects{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Number of goroutines and general load pressure indicator",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (hostname) (nomad_runtime_num_goroutines{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Raft", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Raft Last Contact",
   "type": "timeseries",
   "description": "Time since last contact to leader. General indicator of Raft latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (hostname) (nomad_raft_leader_lastContact{cluster=\"$cluster\",quantile=\"0.99\"})",
     "legendFormat": "p99 - {{hostname}}"
    }
   ]
  },
  {
   "title": "Raft Transactions",
   "type": "timeseries",
   "description": "Number of Raft transactions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (hostname) (rate(nomad_raft_appliedIndex{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raft Dispatch Log",
   "type": "timeseries",
   "description": "Time elapsed to write log, mark in flight, and start replication",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nomad_raft_leader_dispatchLog{cluster=\"$cluster\",quantile=\"0.9\"}",
     "legendFormat": "Time"
    },
    {
     "expr": "increase(nomad_raft_leader_dispatchNumLogs{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Memberlist Gossip",
   "type": "timeseries",
   "description": "Time elapsed to broadcast gossip messages",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (hostname)  (rate(nomad_memberlist_gossip_sum{cluster=\"$cluster\"}[5m]))\n/\n  sum by (hostname) (rate(nomad_memberlist_gossip_count{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raft Apply Count",
   "type": "timeseries",
   "description": "Number of Raft transactions - general indicator of the write load on the servers.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nomad_raft_apply{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Raft Commit Time",
   "type": "timeseries",
   "description": "Time difference between when a message was first passed into Raft and when the resulting commit took place on the leader",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nomad_raft_commitTime{cluster=\"$cluster\",quantile=\"0.9\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Raft Append Entries",
   "type": "timeseries",
   "description": "The time it takes for a Raft transaction to be replicated to a quorum of followers",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nomad_raft_rpc_appendEntries{cluster=\"$cluster\",quantile=\"0.9\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Raft FSM apply",
   "type": "timeseries",
   "description": "Time it takes for a server to apply Raft entries to the internal state machine.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nomad_raft_fsm_apply{cluster=\"$cluster\",quantile=\"0.9\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "RPC Requests",
   "type": "timeseries",
   "description": "Number of RPC requests being handled",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (hostname) (rate(nomad_nomad_rpc_request{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Queries",
   "type": "timeseries",
   "description": "Number of RPC queries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "sum by (hostname) (rate(nomad_nomad_rpc_query{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Errors",
   "type": "timeseries",
   "description": "Number of RPC requests being handled that result in an error",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "sum by (hostname) (rate(nomad_nomad_rpc_request_error{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Evaluations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Evaluations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by (cluster) (nomad_nomad_broker_total_blocked{cluster=\"$cluster\"})",
     "legendFormat": "Blocked"
    },
    {
     "expr": "sum by (cluster) (nomad_nomad_broker_total_ready{cluster=\"$cluster\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum by (cluster) (nomad_nomad_broker_total_unacked{cluster=\"$cluster\"})",
     "legendFormat": "Pending"
    }
   ]
  },
  { "title": "Vault", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Server token TTL",
   "type": "table",
   "description": "Time to live for Vault token",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nomad_nomad_vault_token_ttl{cluster=\"$cluster\"}",
     "legendFormat": "ttl"
    }
   ]
  },
  {
   "title": "Token Last Renew",
   "type": "table",
   "description": "Time since last successful Vault token renewal",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nomad_nomad_vault_token_last_renewal{cluster=\"$cluster\"}",
     "legendFormat": "ttl"
    }
   ]
  },
  {
   "title": "Token Next Renew",
   "type": "table",
   "description": "Time until next Vault token renewal attempt",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nomad_nomad_vault_token_next_renewal{cluster=\"$cluster\"}",
     "legendFormat": "ttl"
    }
   ]
  },
  {
   "title": "Tokens",
   "type": "timeseries",
   "description": "Time elapsed to manipulate Vault tokens",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "nomad_nomad_vault_create_token{cluster=\"$cluster\",quantile=\"0.9\"}",
     "legendFormat": "create"
    },
    {
     "expr": "nomad_nomad_vault_lookup_token{cluster=\"$cluster\",quantile=\"0.9\"}",
     "legendFormat": "lookup"
    },
    {
     "expr": "nomad_nomad_vault_revoke_token{cluster=\"$cluster\",quantile=\"0.9\"}",
     "legendFormat": "revoke"
    }
   ]
  }
 ]
}