{
 "title": "Nomad",
 "description": "Nomad Server Jobs and Alloc",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Host CPU 0 Total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_host_cpu_total{cpu=\"cpu0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host CPU 1 Total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_host_cpu_total{cpu=\"cpu1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alloc CPU Total %",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_allocs_cpu_total_percent",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Mem Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nomad_client_host_memory_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Host Mem Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nomad_client_host_memory_used", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Host CPU Idle",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nomad_client_host_cpu_idle", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Host Mem Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_host_memory_available",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Run Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "nomad_nomad_job_status_running", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Dead Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "nomad_nomad_job_status_dead", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Job Alloc Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "nomad_nomad_job_allocations_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated CPU",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nomad_client_allocated_cpu", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Client Uptime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nomad_client_uptime{datacenter=\"nuc\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}